title: Han SN Ngo
description: A thinker. A coder. And a life lover.
email: han.sn.ngo@gmail.com

menu:
- {name: About Me, url: '#about-me'}
- {name: Portfolio, url: '#portfolio'}
- {name: Blog, url: '#blog'}
 

blurb: >
  Hi! I'm Hannie, born and raised in Vietnam, currently living in Boulder, CO. 
  I almost complete my BS in Computer Science huraay!   
  Biggest part of me loves trying and exploring new things, solving problems and optimizing routines!
  On the side, I love programming and love to think about intelligence, specifically how human 
  intelligence arises and could be replicated on machines. I hope my blog can light up some eager minds
  who  feel the same fascination towards tech and share the same passion as I do!  
  
  Check out my [_**resume**_](https://www.dropbox.com/s/pfhjknf3uc7x5o0/HannieSN_CV.pdf?dl=0){:target="_blank"} and ping me on social media! 
 

social:
- {icon: 'twitter', link: 'http://twitter.com/devtipsshow'}
- {icon: 'dribbble', link: 'https://dribbble.com/travisneilson'}
- {icon: 'behance', link: 'https://www.behance.net/travisneilson'}
- {icon: 'youtube', link: 'https://www.youtube.com/DevTipsForDesigners'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/travisneilson/'}


 